### ISSUE TITLE
BIP-44 adherence 

### ISSUE THREAD

**Issue by aphexmunky** [ava-labs/core-extension#70]
Core wallet doesn't seem to follow some of the important aspects of BIP-44, specifically the iteration through key paths for X and P chain to not reuse addresses that have UTXOs. It's a really important aspect and the web wallet it superseded followed it.

**Comment by gergelylovas** [comment]
Yes, this is correct. It was an intentional decision to reuse addresses in Core instead of generating a new address each time. Even though it's non-compliant, we decided to provide a better user experience. By making this change, we made interacting with the X and P chain similar to how accounts on EVM work, which is a much more familiar concept for most users. Furthermore, based on our experience with the web wallet, we have observed that using a large number of addresses introduced performance issues, from simply loading the wallet balance all the way to signing transactions, especially with hardware wallets.

We provide the option to define the reward address in our staking flows on Core Web for more advanced users wanting to use a new address each time.
